"""update facilities

Revision ID: 6224fd02f1bd
Revises: 8405179a9897
Create Date: 2025-05-24 22:30:44.276587

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6224fd02f1bd"
down_revision: Union[str, None] = "8405179a9897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "facilities", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facilities", type_="unique")
    # ### end Alembic commands ###
