"""upgrade bookings 2

Revision ID: 563e24c0e65e
Revises: a57c42a11df3
Create Date: 2025-04-09 03:08:55.814514

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "563e24c0e65e"
down_revision: Union[str, None] = "a57c42a11df3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
